import React from 'react';

const TermsAndConditionsPage = () => {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white dark:bg-slate-800 shadow-xl rounded-lg p-6 md:p-8 lg:p-10 prose dark:prose-invert max-w-4xl mx-auto">
          <h1 className="text-3xl font-bold mb-6 text-green-700 dark:text-green-500">
            Terms and Conditions
          </h1>
        
          <p>
            This document is an electronic record in terms of the Information Technology Act, 2000, and the rules thereunder as applicable, including the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p className="text-gray-700 mb-6 leading-relaxed">
          <p>
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name sarkhotnaturalfarms.com, including the related mobile site and mobile application (hereinafter referred to as the “Platform”).
          </p>
          <p>
            The Platform is owned by Sarkhot Natural Farms, a registered entity with its office at (Address of Sarkhot Natural Farms) (hereinafter referred to as “Platform Owner”, “we”, “us”, or “our”).
          </p>
          <p>
            Your use of the Platform, services, and tools is governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform, including the applicable policies which are incorporated herein by reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transactions. By merely using the Platform, you shall be contracting with the Platform Owner, and these terms and conditions, including the policies, shall constitute your binding obligations with the Platform Owner.
          </p>
          <p>
            These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by you that are in addition to or conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect.
          </p>
          <p>
            These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates. For the purpose of these Terms of Use, wherever the context so requires, “you”, “your”, or “user” shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
          <p className="font-semibold">
            ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
          </p>
          <p>
            The use of the Platform and/or availing of our Services is subject to the following Terms of Use:
          </p>
      </p>
      <p>
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name sarkhotnaturalfarms.com, including the related mobile site and mobile application (hereinafter referred to as the “Platform”).
      </p>
      <p>
        The Platform is owned by Sarkhot Natural Farms, a registered entity with its office at (Address of Sarkhot Natural Farms) (hereinafter referred to as “Platform Owner”, “we”, “us”, or “our”).
      </p>
      <p>
        Your use of the Platform, services, and tools is governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform, including the applicable policies which are incorporated herein by reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transactions. By merely using the Platform, you shall be contracting with the Platform Owner, and these terms and conditions, including the policies, shall constitute your binding obligations with the Platform Owner.
      </p>
      <p>
        These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by you that are in addition to or conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect.
      </p>
      <p>
        These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates. For the purpose of these Terms of Use, wherever the context so requires, “you”, “your”, or “user” shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
      </p>
      <p className="font-semibold">
        ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
      </p>
      <p>
        The use of the Platform and/or availing of our Services is subject to the following Terms of Use:
      </p>

      <h2>
        1. User Registration & Information
      </h2>
      <p>
        To access and use the Services, you agree to provide true, accurate, and complete information during registration and after. You shall be responsible for all acts done through the use of your registered account on the Platform.
      </p>

      <h2>
        2. No Warranties
      </h2>
      <p>
        Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
      </p>

      <h2>
        3. User Discretion
      </h2>
      <p>
        Your use of our Services and the Platform is solely at your own risk and discretion, for which we shall not be liable. You are required to independently assess and ensure that the Services meet your requirements.
      </p>

      <h2>
        4. Intellectual Property
      </h2>
      <p>
        The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents, including but not limited to design, layout, look, and graphics.
      </p>

      <h2>
        5. Unauthorized Use
      </h2>
      <p>
        You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
      </p>

      <h2>
        6. Payment Obligations
      </h2>
      <p>
        You agree to pay us the charges associated with availing of the Services.
      </p>

      <h2>
        7. Prohibited Use
      </h2>
      <p>
        You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, Indian law, or local laws that might apply to you.
      </p>

      <h2>
        8. Third-Party Links
      </h2>
      <p>
        The Platform and the Services may contain links to third-party websites. Upon accessing these links, you will be governed by the terms of use, privacy policy, and other policies of such third-party websites. These links are provided for your convenience only.
      </p>

      <h2>
        9. Legal Binding
      </h2>
      <p>
        Upon initiating a transaction for availing of the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
      </p>

      <h2>
        10. Indemnity
      </h2>
      <p>
        You agree to indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claims, demands, or actions, including reasonable attorney’s fees, made by any third party arising out of your breach of these Terms of Use, Privacy Policy, other policies, or your violation of any law, rules, or regulations or the rights (including infringement of intellectual property rights) of a third party.
      </p>

      <h2>
        11. Limitation of Liability
      </h2>
      <p>
        In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data, or other economic interests, whether in contract, negligence, tort, or otherwise, arising from the use of or inability to use the Services, however caused, and whether arising in contract, tort, negligence, warranty, or otherwise. Our liability shall not exceed the amount paid by you for using the Services, or Rupees One Hundred (Rs. 100), whichever is less.
      </p>

      <h2>
        12. Force Majeure
      </h2>
      <p>
        Notwithstanding anything contained in these Terms of Use, neither party shall be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
      </p>

      <h2>
        13. Governing Law & Jurisdiction
      </h2>
      <p>
        These Terms and any disputes or claims relating to them, or their enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in India.
      </p>

      <h2>
        14. Contact Information
      </h2>
      <p>
        All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
      </p>

      <p>
        Sarkhot Natural farms denote the community of natural farmers. Natural means 💯% chemical free, preservative free and poison free.
      </p>
        </div>
      </div>
    </div>
  ); // Correctly closing the three main divs within return
};

export default TermsAndConditionsPage;
